GET http://localhost:8001/api/cards

###

POST http://localhost:8001/api/cards
Content-Type: application/json

{
    "card_name": "lightning bolt"
}

###

GET http://localhost:8002/api/cards

###

POST http://localhost:8002/api/cards
Content-Type: application/json

{
    "card_name": "path to exile"
}

