# get all cards - quarkus
GET http://localhost:8001/api/cards

###
# save a card - quarkus
POST http://localhost:8001/api/cards
Content-Type: application/json

{
    "name": "lightning bolt"
}

###
# get all cards - spring boot
GET http://localhost:8002/api/cards

###
# save a card - spring boot
POST http://localhost:8002/api/cards
Content-Type: application/json

{
    "card_name": "path to exile"
}

