spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/card_db
    username: db_user
    password: db_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        formatsql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8002